[tool.ruff]
line-length = 120
exclude = [".git", "__pycache__", "*.egg", "build", ".pytype", ".mypy_cache"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.main]
ignore-paths = ["\\.git", "__pycache__", ".*\\.egg", "build", "\\.pytype", "\\.mypy_cache"]

[tool.black] 
line-length = 120
target-version = ['py311']
exclude = "/(\\.direnv|\\.eggs|\\.git|\\.mypy_cache|\\.nox|\\.tox|\\.venv|venv|\\.ipynb_checkpoints|_build|buck-out|build|dist|__pypackages__|\\.pytype)/"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.pytype]
python_version = "3.11"

[tool.fixit]
root = true
python-version = "3.11"
formatter = "black"

